[build-system]
requires = ["setuptools", "wheel", "os"]
build-backend = "setuptools.build_meta"

[project]
name = "zplot_tools"
version = "0.0.1"
description = "Personal package with matplotlib styles and other helpers"
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/zaitam/zplot-tools"

[tool.setuptools]
packages = ["zplot_tools"]

[tool.setuptools.package-data]
"zplot_tools.mpl_styles" = ["*.mplstyle"]